from __future__ import annotations

import sys
from pathlib import Path


def _pem_to_c_array(name: str, pem_text: str) -> str:
    lines = pem_text.strip().splitlines()
    parts = [f'static const char {name}[] PROGMEM =']
    for line in lines:
        parts.append(f'    "{line}\\n"')
    parts[-1] += ";"
    return "\n".join(parts)


def main() -> int:
    if len(sys.argv) != 4:
        print("Usage: make_header.py <cert.pem> <key.pem> <out.h>")
        return 1

    cert_path = Path(sys.argv[1]).resolve()
    key_path = Path(sys.argv[2]).resolve()
    out_path = Path(sys.argv[3]).resolve()

    cert_pem = cert_path.read_text(encoding="utf-8")
    key_pem = key_path.read_text(encoding="utf-8")

    content = "\n".join(
        [
            "#pragma once",
            "#include <Arduino.h>",
            "",
            "// Auto-generated by certs/make_header.py",
            _pem_to_c_array("kServerCertPem", cert_pem),
            "",
            _pem_to_c_array("kServerKeyPem", key_pem),
            "",
            "static const size_t kServerCertPemLen = sizeof(kServerCertPem);",
            "static const size_t kServerKeyPemLen = sizeof(kServerKeyPem);",
            "",
        ]
    )

    out_path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
