#pragma once
#include <Arduino.h>

// Auto-generated by certs/make_header.py
static const char kServerCertPem[] PROGMEM =
    "-----BEGIN CERTIFICATE-----\n"
    "MIICHzCCAcagAwIBAgIUYcnNnffXWwp4c08Gk85GMhyTpA8wCgYIKoZIzj0EAwIw\n"
    "WzELMAkGA1UEBhMCQ0gxCzAJBgNVBAgMAlZEMREwDwYDVQQHDAhMYXVzYW5uZTEV\n"
    "MBMGA1UECgwMR29Qcm8tQnJpZGdlMRUwEwYDVQQDDAxHb1Byby1CcmlkZ2UwHhcN\n"
    "MjYwNDMwMTM1OTQyWhcNMzYwNDI3MTM1OTQyWjBbMQswCQYDVQQGEwJDSDELMAkG\n"
    "A1UECAwCVkQxETAPBgNVBAcMCExhdXNhbm5lMRUwEwYDVQQKDAxHb1Byby1Ccmlk\n"
    "Z2UxFTATBgNVBAMMDEdvUHJvLUJyaWRnZTBZMBMGByqGSM49AgEGCCqGSM49AwEH\n"
    "A0IABJAFR+gRaxaVOFa48hR0P8QszL9z2SccUaPwIFiQkqBJfsEpdniOGWvS5+OL\n"
    "slKK+U+3T2ImhNRsGq3Dvk7h1R6jaDBmMA8GA1UdEQQIMAaHBMCoBAEwDwYDVR0T\n"
    "AQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAqQwEwYDVR0lBAwwCgYIKwYBBQUHAwEw\n"
    "HQYDVR0OBBYEFH7Nx6J7zb1GdjsABzM5H22n1lcqMAoGCCqGSM49BAMCA0cAMEQC\n"
    "IDAE7iqzHbP3OkrcJYlRZMS6oXGWYtezVGwyQN7dagOGAiAkB1TMDLM+BjCwqbsq\n"
    "oR80Z0JRq1VNHGX5ZIU0IIRmsQ==\n"
    "-----END CERTIFICATE-----\n";

static const char kServerKeyPem[] PROGMEM =
    "-----BEGIN EC PRIVATE KEY-----\n"
    "MHcCAQEEIEHyW6eWorkUSVjcsD93oGI9/UOYSBMgnHUHgYdGeV5ToAoGCCqGSM49\n"
    "AwEHoUQDQgAEkAVH6BFrFpU4VrjyFHQ/xCzMv3PZJxxRo/AgWJCSoEl+wSl2eI4Z\n"
    "a9Ln44uyUor5T7dPYiaE1GwarcO+TuHVHg==\n"
    "-----END EC PRIVATE KEY-----\n";

static const size_t kServerCertPemLen = sizeof(kServerCertPem);
static const size_t kServerKeyPemLen = sizeof(kServerKeyPem);
